[package]
name = "issue-1"
version = "0.1.0"
edition = "2021"
default-run = "issue-1"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.38"
